version: '3.8'

services:
  qurban-app:
    build: .
    container_name: qurban2026-container
    ports:
      - "8085:80"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
